name: mbfron_enes_ali_ovur
description: A new Flutter project.



publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2

  dio: ^4.0.4

  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0

  flutter_dotenv: ^5.0.2

  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  bloc: ^7.2.1
  rxdart: ^0.27.3
 
  path: ^1.8.0
  sembast: ^3.1.1+1
  path_provider: ^2.0.8


  easy_localization: ^3.0.0

  google_fonts: ^2.2.0
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0



flutter:


  uses-material-design: true

 
  assets:
      - assets/lang/
      - .env
      - assets/images/default_book.png
 

